server:
  #端口
  port: 8070
spring:
  application:
    #服务名称
    name: api-gateway-server
  cloud:
    #注册到 nacos中心
    nacos:
      discovery:
        server-addr: http://localhost:8848/
    #配置SpringCould-Gateway路由
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
      routes:
        - id: nacosprovider    # id：我们自定义的路由 ID，保持唯一
          uri: lb://nacos-provider   #  uri：目标服务地址,以lb://开头（lb代表从注册中心获取服务）
          predicates:          #  predicates：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/test/**
            # filters：过滤规则，本示例暂时没用。